services:
  - type: web
    name: attendance-system
    runtime: python
    repo: https://github.com/BrozTech-84/AttendanceSystem
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p $PORT AttendanceSystem.asgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: attendance-redis
          property: connectionString

  - type: redis
    name: attendance-redis
    plan: free

  - type: postgresql
    name: attendance-db
    plan: free