# Generated by Django 6.0.4 on 2026-04-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentScanner', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
