# Generated by Django 6.0.4 on 2026-04-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentScanner', '0004_course_students'),
        ('UserLogin', '0002_customuser_role_alter_program_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(related_name='courses', to='UserLogin.program'),
        ),
    ]
