# Generated by Django 6.0.4 on 2026-04-27 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentScanner', '0005_remove_course_program_course_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='qr_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
