# Generated by Django 6.0.4 on 2026-04-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentScanner', '0006_session_latitude_session_longitude_session_qr_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='qr_code_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
