# Generated by Django 6.0.4 on 2026-05-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentScanner', '0008_alter_attendance_options_attendance_device_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='location_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
