# Generated by Django 6.0.4 on 2026-04-25 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0002_customuser_role_alter_program_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='lecturers', to='UserLogin.program'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='UserLogin.program'),
        ),
    ]
