# Generated by Django 6.0.4 on 2026-04-27 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0003_customuser_programs_alter_customuser_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_users', to='UserLogin.program'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='customuser_lecturers', to='UserLogin.program'),
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('programs', models.ManyToManyField(blank=True, related_name='lecturer_profiles', to='UserLogin.program')),
            ],
        ),
    ]
